config/routes.rb
Rails.application.routes.draw do
  namespace :cooks do
    resources :foods
    resources :recipes
  end

  #get '/cooks/recipes/new/food_search', to: 'cooks/recipes#food_search'
  get '/cooks/recipes/new/:id', to: 'cooks/recipes#food_recipe_show'
  put '/cooks/recipes/new/:id', to: 'cooks/recipes#food_recipe_update'
  patch '/cooks/recipes/new/:id', to: 'cooks/recipes#food_recipe_update'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace :admin do
    resources :users
  end
  
  get '/cooks/search' , to:'cooks#index'
  root to:'cooks#index'
  resources :cooks 

end

app/models/cook.rb
class Cook < ApplicationRecord
    before_validation :set_nameless_name
    validates :start_time, presence: true

    with_options numericality: true do
        validates :protein
        validates :fat
        validates :carbon_hydrate
        validates :amount
    end

    def kcal
        4*protein + 9*fat + 4*carbon_hydrate
    end

    belongs_to :user

    scope :recent, -> { order(start_time: :desc) }

    has_many :foods, through: :cook_foods
    has_many :cook_foods


    private
    
    def set_nameless_name
        self.name = '食べ物' if name.blank? 
    end    
end

app/models/food.rb
class Food < ApplicationRecord
    has_many :recipes, through: :recipes_food
    has_many :recipes_food
    accepts_nested_attributes_for :recipes_food
    paginates_per 10

    def self.csv_attributes
        ["name", "protein", "fat", "carbon_hydrate", "kcal"]
    end

    def self.import(file)
        CSV.foreach('eiyo.csv', headers: true) do |row|
            food = new
            food.attributes = row.to_hash.slice(*csv_attributes)
            food.save!
        end
    end
end

app/controllers/cooks/foods_controller.rb
class Cooks::FoodsController < ApplicationController
  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)

    if @food.save
      redirect_to cooks_foods_path, notice: "食材「#{@food.name}」を登録しました"
    else
      render :new
    end
  end

  def show
  end

  def index
    @q = Food.ransack(params[:q])
    @foods = @q.result(distinct: true).page(params[:page])
    #@foods = Food.all.page(params[:page])
  end

  # def search
  #   @q = Food.search(search_params)
  #   @foods = @q.result(distinct: true)
  # end

  def import
    foods.import(params[:file])
    render :new, notice: "食材を追加しました"
  end

  private

  def food_params
    params.require(:food).permit(:name, :protein, :fat, :carbon_hydrate, :kcal, :amount)
  end

  # def search_params
  #   params.require(:q).permit!
  # end
end

app/controllers/cooks/recipes_controller.rb
class Cooks::RecipesController < ApplicationController
  def new
    
    @recipe = Recipe.new
    #@q = Food.ransack(params[:q])
    #@foods = @q.result(distinct: true).page(params[:page])
    @foods = Food.where('foods.name LIKE(?)', "%#{params[:food_search]}%").page(params[:page])
    #debugger
    @food_recipes = Food.where(flag: false)
  end

  def food_recipe_update
    @food_recipes.update!(food_recipe_params)
    redirect_to new_cooks_recipe_path
    debugger
  end

  def food_update_show
  end

  def food_search
    # @qf = Food.ransack(params[:qf])
    # @foods = @qf.result(distinct: true).page(params[:page])
    @foods = Food.where('foods.name LIKE(?)', "%#{params[:food_search]}%").page(params[:page])
    # @cal_protein = @food.protein * @food.params[:amount] / 100
    # @cal_fat = fat * amount / 100
    # @cal_carbon_hydrate = carbon_hydrate * amount / 100
    # @kcal = cal_protein * 4 + cal_fat * 9 + carbon_hydrate * 4
    @food_recipes = Food.where(flag: false)
    #@cal_protein = Food.select

    
    logger.info(Food.find_by(flag: false))
    logger.info(params[:flag])

    # @user_protein = require_protein.protein
    # @user_fat = require_fat.fat
    # @user_carbon_hydrate = require_carbon_hydrate.carbon_hydrate
    # @user_kcal = require_kcal.kcal

    unless params[:flag].blank?
      logger.debug(params[:flag])
    end

    if :flag == false
      #day = params[:start_time].to_i
      logger.info "ラーメン"
      #logger.info()
    end



  end

  def cal_protein
    @cal_protein = Food(:protein) * :amount /100
  end

  def food_search_update
    @food_recipes.update!(food_recipe_params)
    redirect_to new_cooks_recipe_path
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def edit
  end
  
  def update
    @recipe.update!(recipe_params)
    redirect_to cooks_recipes_path, notice: "食品「#{@recipe.name}」を編集しました"
  end

  def destroy
    @recipe.destroy
    redirect_to cooks_recipes_path, notice: "食品「#{@recipe.name}」を削除しました"
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)

    if @recipe.save
      redirect_to cooks_recipes_path, notice: "レシピ「#{@recipe.name}」を登録しました"
    else
      render :new
    end
  end

  def index
    @q = Recipe.ransack(params[:q])
    @recipes = @q.result(distinct: true).page(params[:page])
  end
  
  private

  def recipe_params
    params.require(:recipe).permit(:name, :protein, :fat, :carbon_hydrate, :kcal, :amount)
  end

  def food_recipe_params
    params.require(:food_search).permit(:name, :protein, :fat, :carbon_hydrate, :kcal, :flag)
  end

  def set_recipe
    @recipe = current_user.recipes.find(params[:id])

  end

end

app/controllers/cooks_controller.rb
class CooksController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_cook, only: [:show, :edit, :update, :destroy]

  def index
    unless params[:date].blank?
      if params[:date][:month].to_i < 10
        start_time_month = "0" + params[:date][:month]
      else
        start_time_month = params[:date][:month]
      end

      if params[:date][:day].to_i < 10
        start_time_day = "0" + params[:date][:day]
      else
        start_time_day = params[:date][:day]
      end

      unless params[:date][:year].blank? && start_time_month.blank? && start_time_day .blank?

        start_time_string_date = (params[:date][:year] + "-" + start_time_month + "-" + start_time_day).to_date
      #@cooks = current_user.cooks.order(start_time: :desc).where(start_time: start_time_string_date)
      end
      
    end
    @cooks = current_user.cooks.order(start_time: :desc).where(start_time: start_time_string_date)
    logger.info(start_time_string_date)

    # @user_protein = require_protein.protein
    # @user_fat = require_fat.fat
    # @user_carbon_hydrate = require_carbon_hydrate.carbon_hydrate
    # @user_kcal = require_kcal.kcal

    unless params[:date].blank?
      logger.debug(params[:date][:year])
      logger.debug(params[:date][:month])
      logger.debug(params[:date][:day])
      #logger.debug(params[:date])
    end

    unless :start_time.blank?
      #day = params[:start_time].to_i
      logger.info "ラーメン"
      #logger.info()
    end
  end

  def show
 
  end

  def new
    @cook = Cook.new
  end

  def edit
  end
  
  def update
    @cook.update!(cook_params)
    redirect_to cooks_url, notice: "食品「#{@cook.name}」を編集しました"
  end

  def destroy
    @cook.destroy
    redirect_to cooks_url, notice: "食品「#{@cook.name}」を削除しました"
  end

  def create
    @cook = current_user.cooks.new(cook_params)

    if @cook.save
      redirect_to new_cook_path, notice: "食品「#{@cook.name}」を登録しました"
    else
      render :new
    end
  end

  #def search
    #@q = cooks.ransack[params[:q]]
    #@cooks = @q.result(distinct: true).recent
  #end


  private

  def cook_params
    params.require(:cook).permit(:name, :protein, :fat, :carbon_hydrate, :amount, :start_time)
    
  end

  def cook_kcal
    cook_params.merge(@cook.kcal)
  end

  def set_cook
    @cook = current_user.cooks.find(params[:id])
  end
end

app/helpers/cooks/foods_helper.rb
module Cooks::FoodsHelper
end

app/helpers/cooks/recipes_helper.rb
module Cooks::RecipesHelper
end

app/views/cooks/foods/edit.html.slim
h1 Cooks::Foods#edit
p Find me in app/views/cooks/foods/edit.html.slim

app/views/cooks/foods/index.html.slim
h1 食材一覧
= link_to '食材追加', new_cooks_food_path,  class: 'btn btn-primary mr-3'

= search_form_for @q, url: cooks_foods_path, class: 'mb-5' do |f|
  .form-group.row 
    = f.label :name_cont, '食材名', class: 'col-sm-2 col-form-label'
    .col-sm-10 
      = f.search_field :name_cont, class: 'form-control', required: true
  .form-group 
    = f.submit class: 'btn btn-outline-primary'

.mb-3 
  = paginate @foods
  = page_entries_info @foods

table.table.table-hover
  h2 検索結果
  thead.thead-default
    tr 
      th= Food.human_attribute_name(:name)
      th= Food.human_attribute_name(:protein)
      th= Food.human_attribute_name(:fat)
      th= Food.human_attribute_name(:carbon_hydrate)
      th= Food.human_attribute_name(:kcal)
      th

  tbody 
    -unless @foods.blank? 
      - @foods.each do |food|
            tr 
              td= food.name 
              td= food.protein 
              td= food.fat 
              td= food.carbon_hydrate 
              td= food.protein.to_i*4 + food.fat.to_i*9 + food.carbon_hydrate.to_i*4
              td
                = link_to '編集', edit_cooks_food_path(food), class: 'btn btn-primary mr-3'
                = link_to '削除', cooks_food_path(food), method: :delete, data: { confirm: "削除しますか？" }, class: 'btn btn-primary mr-3'    

app/views/cooks/foods/new.html.slim
h1 食材の登録
h5 ※100g当たりの数値を記入してください

- if @food.errors.present?
  ul#error_explanation 
    - food.errors.full_messages.each do |message|
      li= message

= form_with model: @food, url: cooks_foods_path, local: true do |f| 
  .form-group 
    = f.label :name
    = f.text_field :name, class: 'form-control', id: 'food_name'
  .form-group 
    = f.label :protein
    = f.text_field :protein, class: 'form-control', id: 'food_protein'
  .form-group 
    = f.label :fat
    = f.text_field :fat, class: 'form-control', id: 'food_fat'
  .form-group 
    = f.label :carbon_hydrate
    = f.text_field :carbon_hydrate, class: 'form-control', id: 'food_carbon_hydrate'
  /.form-group 
    = f.label :kcal
    = f.text_field :kcal, value: @kcal, class: 'form-control', id: 'food_kcal'
  /.form-group 
    = f.label :amount
    = f.text_field :amount, class: 'form-control', id: 'food_amount'
  = f.submit nil, class: 'btn btn-primary'

app/views/cooks/foods/show.html.slim
h1 食材詳細

.nav.justify-content-end 
  = link_to '戻る', cooks_foods_path, class: 'nav-link'

table.table.table-hover 
  tbody 
    tr 
      th= Food.human_attribute_name(:name)
      td= @food.name
    tr 
      th= Food.human_attribute_name(:protein)
      td= @food.protein
    tr 
      th= Food.human_attribute_name(:fat)
      td= @food.fat
    tr 
      th= Food.human_attribute_name(:carbon_hydrate)
      td= @food.carbon_hydrate
    tr 
      th= Food.human_attribute_name(:amount)
      td= @food.amount
    
= link_to '編集', edit_cooks_food_path, class: 'btn btn-primary mr-3'
= link_to '削除', @food, method: :delete, data: { confirm: "削除しますか？" }, class: 'btn btn-primary mr-3'