config/routes.rb
Rails.application.routes.draw do
  namespace :cooks do
    resources :foods
    resources :recipes
  end

  #get '/cooks/recipes/new/food_search', to: 'cooks/recipes#food_search'
  get '/cooks/recipes/new/:id', to: 'cooks/recipes#food_recipe_show'
  put '/cooks/recipes/new/:id', to: 'cooks/recipes#food_recipe_update'
  patch '/cooks/recipes/new/:id', to: 'cooks/recipes#food_recipe_update'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace :admin do
    resources :users
  end
  
  get '/cooks/search' , to:'cooks#index'
  root to:'cooks#index'
  resources :cooks 

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    
    validates :name, presence: true
    validates :email, presence: true, uniqueness: true

    with_options numericality: true do
        validates :body_mass, allow_nil: true
        validates :body_fat_percentage, allow_nil: true
        validates :tall, allow_nil: true
        validates :age, allow_nil: true
    end

    has_many :cooks
    has_many :recipes

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :login_required, only: [:index, :edit, :update, :destroy]
  helper_method :bm_male, :bm_female, :require_kcal, :require_protein, :require_fat, :require_carbon_hydrate

  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_user_url(@user), notice: "ユーザー「#{@user.name}」を登録しました"
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_user_url(@user), notice: "ユーザー「#{@user.name}」を更新しました"
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_url, notice: "ユーザー「#{@user.name}」を削除しました"
  end

  unless  :tall.blank? || :age.blank? || :body_mass.blank? || :sex.blank? || :activity_level.blank? || :purpose.blank?

    def bm_male
        if @user.activity_level == '1'
            ( (10 * @user.body_mass) + (6.25 * @user.tall) - (5 * @user.age) + 5 ) * 1.725
        elsif @user.activity_level == '2'
            ( (10 * @user.body_mass) + (6.25 * @user.tall) - (5 * @user.age) + 5 ) * 1.55
        else
            ( (10 * @user.body_mass) + (6.25 * @user.tall) - (5 * @user.age) + 5 ) * 1.2
        end
    end

    def bm_female
        if @user.activity_level == '1'
            ( (10 * @user.body_mass) + (6.25 * @user.tall) - (5 * @user.age) - 161 ) * 1.725
        elsif @user.activity_level == '2'
            ( (10 * @user.body_mass) + (6.25 * @user.tall) - (5 * @user.age) - 161 ) * 1.55
        else
            ( (10 * @user.body_mass) + (6.25 * @user.tall) - (5 * @user.age) - 161 ) * 1.2
        end
    end

    def require_kcal
        if @user.sex == 1
            if @user.purpose == '1'
                bm_male * 1.2
            elsif @user.purpose == '2'
                bm_male * 1
            else 
                bm_male * 0.8
            end
        else
            if @user.purpose == '1'
                bm_female * 1.2
            elsif @user.purpose == '2'
                bm_female * 1
            else 
                bm_female * 0.8
            end
        end
    end

    def require_protein
        @user.body_mass * 2
    end

    def require_fat
        require_kcal * 0.25 / 9
    end

    def require_carbon_hydrate
        (require_kcal - (require_protein * 4) - (require_fat * 9) ) / 4
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation, 
      :body_mass, :body_fat_percentage, :purpose, :activity_level, :tall, :age, :sex)
  end

  def require_admin
    redirect_to root_url unless current_user.admin?
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.slim
- if user.errors.present?
  ul#error_explanation 
    - user.errors.full_messages.each do |message|
      li= message

= form_with model: [:admin, @user], local: true do |f|
  .form-group 
    = f.label :name, '名前'
    = f.text_field :name, class: 'form-control'
  .form-group 
    = f.label :email, 'メールアドレス'
    = f.text_field :email, class: 'form-control'
  .form-group 
    = f.label :password, 'パスワード'
    = f.password_field :password, class: 'form-control'
  .form-group 
    = f.label :password_confirmation, 'パスワード(確認)'
    = f.password_field :password_confirmation, class: 'form-control'
  .form-group 
    = f.label :body_mass, '体重(任意)'
    = f.text_field :body_mass, class: 'form-control'
  .form-group 
    = f.label :tall, '身長(任意)'
    = f.text_field  :tall, class: 'form-control'
  .form-group 
    = f.label :age, '年齢(任意)'
    = f.text_field  :age, class: 'form-control'
  .form-group 
    = f.label :sex, '性別(任意)'
    = f.select  :sex, {'男性': 1, '女性': 2, 'その他': 3}, { iclude_blank: '選択してください' }, class: 'form-control'
  .form-group 
    = f.label :purpose, '目的(任意)'
    = f.select :purpose, {'増量': 1, '維持': 2, '減量': 3}, { iclude_blank: '選択してください' }, class: 'form-control'
  .form-group 
    = f.label :activity_level, '活動レベル(任意)'
    = f.select  :activity_level, {'高': 1, '中': 2, '低': 3}, { iclude_blank: '選択してください' }, class: 'form-control'
  = f.submit '登録する', class: 'btn btn-primary'

app/views/admin/users/edit.html.slim
h1 ユーザー情報編集

.nav.justify-content-end  
  = link_to '一覧', admin_users_path, class: 'nav-link'

= render partial: 'form', locals: { user: @user }

app/views/admin/users/index.html.slim
h1 ユーザー一覧

= link_to '新規登録', new_admin_user_path, class: 'btn btn-primary'


.mb-3 
table.table.table-hover
  thead.thead-default
    tr 
      th= User.human_attribute_name(:name)
      th= User.human_attribute_name(:email)
      th= User.human_attribute_name(:admin)
      th= User.human_attribute_name(:body_mass)
      th= User.human_attribute_name(:body_fat_percentage)
      th= User.human_attribute_name(:tall)
      th= User.human_attribute_name(:age)
      th= User.human_attribute_name(:purpose)
      th= User.human_attribute_name(:activity_level)
      th= User.human_attribute_name(:created_at)
      th= User.human_attribute_name(:updated_at)
      th

  tbody 
    - @users.each do |user|
      tr 
        td= link_to user.name, [:admin, user]
        td= user.email
        td= user.admin? ? 'あり' : 'なし'
        td= user.body_mass
        td= user.body_fat_percentage 
        td= user.tall
        td= user.age
        td= user.purpose
        td= user.activity_level
        td= user.created_at
        td= user.updated_at
        td
          = link_to '編集', edit_admin_user_path(user), class: 'btn btn-primary mr-3'
          = link_to '削除', [:admin, user], method: :delete, data: { confirm: "削除しますか？" }, class: 'btn btn-danger mr-3'

app/views/admin/users/new.html.slim
h1 ユーザー登録

= render partial: 'form', locals: { user: @user }

app/views/admin/users/show.html.slim
h1 ユーザー情報詳細

.nav.justify-content-end 
  = link_to '戻る', cooks_path, class: 'nav-link'

table.table.table-hover 
  tbody 
    tr 
      th= User.human_attribute_name(:id)
      td= @user.id
    tr 
      th= User.human_attribute_name(:name)
      td= @user.name
    tr 
      th= User.human_attribute_name(:email)
      td= @user.email
    tr 
      th= User.human_attribute_name(:body_mass)
      td= @user.body_mass
    tr 
      th= User.human_attribute_name(:body_fat_percentage)
      td= @user.body_fat_percentage
    tr 
      th= User.human_attribute_name(:tall)
      td= @user.tall
    tr 
      th= User.human_attribute_name(:age)
      td= @user.age
    tr 
      th= User.human_attribute_name(:sex)

      - if @user.sex == 1
          td= '男性' 
      - elsif @user.sex == 2
          td= '女性'
      - else 
          td= 'その他'
    tr 
      th= User.human_attribute_name(:purpose)
      - if @user.purpose == "1"
          td= '増量' 
      - elsif @user.purpose == "2"
          td= '維持'
      - else 
          td= '減量'
    tr 
      th= User.human_attribute_name(:activity_level)
      - if @user.activity_level == "1"
          td= '高' 
      - elsif @user.activity_level == "2"
          td= '中'
      - else 
          td= '低'

- unless  @user.tall.blank? || @user.age.blank? || @user.body_mass.blank? || @user.sex.blank? || @user.activity_level.blank? || @user.purpose.blank?
  .content
    h2 目標値
  .mb-10
  table.table.table-hover
    thead.thead-default
      tr 
        th= User.human_attribute_name(:protein)
        th= User.human_attribute_name(:fat)
        th= User.human_attribute_name(:carbon_hydrate)
        th= User.human_attribute_name(:kcal)
        th
        
      tbody 
        
          tr 
            td= require_protein.round(1)
            td= require_fat.round(1)
            td= require_carbon_hydrate.round(1)
            td= require_kcal.round(1)

= link_to '編集', edit_admin_user_path, class: 'btn btn-primary mr-3'
= link_to '削除', [:admin, @user], method: :delete, data: { confirm: "削除しますか？" }, class: 'btn btn-danger'