config/routes.rb
Rails.application.routes.draw do
  namespace :cooks do
    resources :foods
    resources :recipes
  end

  #get '/cooks/recipes/new/food_search', to: 'cooks/recipes#food_search'
  get '/cooks/recipes/new/:id', to: 'cooks/recipes#food_recipe_show'
  put '/cooks/recipes/new/:id', to: 'cooks/recipes#food_recipe_update'
  patch '/cooks/recipes/new/:id', to: 'cooks/recipes#food_recipe_update'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace :admin do
    resources :users
  end
  
  get '/cooks/search' , to:'cooks#index'
  root to:'cooks#index'
  resources :cooks 

end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | ダイエットアプリ
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light
      .navbar-brand ダイエットアプリ

      ul.navbar-nav.ml-auto
         - if current_user
           li.nav-item = link_to '食材追加', cooks_foods_path, class: 'nav-link'
           li.nav-item = link_to 'レシピ登録', cooks_recipes_path, class: 'nav-link'
           li.nav-item = link_to '食事登録', cooks_path, class: 'nav-link'
           li.nav-item = link_to 'ユーザー情報', admin_user_path(current_user), class: 'nav-link'
           li.nav-item = link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link'
         - else
           li.nav-item = link_to '会員登録', new_admin_user_path, class: 'nav-link'
           li.nav-item = link_to 'ログイン', login_path, class: 'nav-link'

    .container
      - if flash.notice.present?
        .alert.alert-success = flash.notice
      = yield